blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='blog_index'),  # http://127.0.0.1
    url(r'^(?P<blog_id>[0-9]+)/$', views.detail, name='blog_detail'),
    url(r'^category/(?P<category_id>[0-9]+)/$', views.category, name='blog_category'),
    url(r'^tag/(?P<tag_id>[0-9]+)/$', views.tag, name='blog_tag'),
    url(r'^archives/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$', views.archives, name='blog_archives'),
    url(r'^search/$', views.search, name='blog_search'),
    url(r'^reply/(?P<comment_id>\d+)/$', views.reply, name='comment_reply'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=128, verbose_name='博客分类')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = '博客分类'


class Tag(models.Model):

    name = models.CharField(max_length=128, verbose_name='博客标签')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客标签'
        verbose_name_plural = '博客标签'


class Entry(models.Model):

    title = models.CharField(max_length=128, verbose_name='文章标题')

    author = models.ForeignKey(User, verbose_name='博客作者')

    img = models.ImageField(upload_to='blog_images', null=True, blank=True, verbose_name='博客配图')

    body = RichTextUploadingField(verbose_name='博客正文')

    abstract = models.TextField(max_length=256, blank=True, null=True, verbose_name='博客摘要')

    visiting = models.PositiveIntegerField(default=0, verbose_name='访问量')

    category = models.ManyToManyField(Category, verbose_name='博客分类')

    tags = models.ManyToManyField(Tag, verbose_name='博客标签')

    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    modified_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog_detail', kwargs={'blog_id': self.id})  # http://127.0.0.1/blog/3

    def increase_visting(self):
        self.visiting += 1
        self.save(update_fields=['visiting'])

    class Meta:
        ordering = ['-created_time']
        verbose_name = '博客'
        verbose_name_plural = '博客'

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.conf import settings
from django_comments.models import Comment

import markdown
import pygments
import requests
import json

from . import models
from utils.mypage import Page


def index(request):
    entries = models.Entry.objects.all()

    if entries:
        entries_count = entries.count()
        page_num = request.GET.get('page', 1)
        url_prefix = "/blog/?"
        page_obj = Page(page_num=page_num, total_count=entries_count, per_page=10, url_prefix=url_prefix, max_page=5)
        entries = entries[page_obj.start:page_obj.end]
        page_html = page_obj.page_html()
        return render(request, 'blog/index.html', locals())

    else:
        error_msg = '暂无文章'
        return render(request, 'blog/index.html', {
            'error_msg': error_msg,
        })


def detail(request, blog_id):
    entry = get_object_or_404(models.Entry, id=blog_id)
    entry.increase_visting()

    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    entry.body = md.convert(entry.body)
    entry.toc = md.toc

    comment_list = list()

    def get_comment_list(comments):
        for comment in comments:
            comment_list.append(comment)
            children = comment.child_comment.all()
            if len(children) > 0:
                get_comment_list(children)

    top_comments = Comment.objects.filter(object_pk=blog_id, parent_comment=None, content_type__app_label='blog').order_by('-submit_date')
    get_comment_list(top_comments)

    return render(request, 'blog/detail.html', locals())


def category(request, category_id):
    c = get_object_or_404(models.Category, id=category_id)
    entries = models.Entry.objects.filter(category=c)

    if entries:
        entries_count = entries.count()
        page = request.GET.get('page', 1)
        url_prefix = "/blog/category/{}/?".format(category_id)
        page_obj = Page(page_num=page, total_count=entries_count, per_page=10, url_prefix=url_prefix, max_page=5)
        entries = entries[page_obj.start:page_obj.end]
        page_html = page_obj.page_html()

        return render(request, 'blog/index.html', locals())

    else:
        error_msg = '该分类下暂无文章'
        return render(request, 'blog/index.html', {
            'error_msg': error_msg,
        })


def tag(request, tag_id):
    tag = get_object_or_404(models.Tag, id=tag_id)
    entries = models.Entry.objects.filter(tags=tag)

    if entries:
        entries_count = entries.count()
        page = request.GET.get('page', 1)
        url_prefix = "/blog/tag/{}/?".format(tag_id)
        page_obj = Page(page_num=page, total_count=entries_count, per_page=10, url_prefix=url_prefix, max_page=5)
        entries = entries[page_obj.start:page_obj.end]
        page_html = page_obj.page_html()

        return render(request, 'blog/index.html', locals())

    else:
        error_msg = '此标签下暂无文章'
        return render(request, 'blog/index.html', {
            'error_msg': error_msg,
        })


def search(request):
    keyword = request.GET.get('keyword', None)
    if not keyword:
        return redirect('/blog/')

    entries = models.Entry.objects.filter(Q(title__icontains=keyword)
                                          | Q(body__icontains=keyword)
                                          | Q(abstract__icontains=keyword))

    if entries:
        total_count = entries.count()
        page_num = request.GET.get('page', 1)
        url_prefix = "/blog/search/?keyword={}".format(keyword)
        page_obj = Page(page_num=page_num, total_count=total_count, per_page=10, url_prefix=url_prefix, max_page=5)
        entries = entries[page_obj.start:page_obj.end]
        page_html = page_obj.page_html()

        return render(request, 'blog/index.html', locals())

    else:
        error_msg = '没有与此关键词匹配的文章'
        return render(request, 'blog/index.html', {
            'error_msg': error_msg,
        })


def archives(request, year, month):
    entries = models.Entry.objects.filter(created_time__year=year, created_time__month=month)

    if entries:
        entries_count = entries.count()
        page = request.GET.get('page', 1)
        url_prefix = "/blog/archives/{0}/{1}/?".format(year, month)
        page_obj = Page(page_num=page, total_count=entries_count, per_page=10, url_prefix=url_prefix, max_page=5)
        entries = entries[page_obj.start:page_obj.end]
        page_html = page_obj.page_html()

        return render(request, 'blog/index.html', locals())

    else:
        return render(request, 'blog/404.html', locals())


def permission_denied(request):
    return render(request, 'blog/403.html', locals())


def page_not_found(request):
    return render(request, 'blog/404.html', locals())


def page_error(request):
    return render(request, 'blog/500.html', locals())


def login(request):
    code = request.GET.get('code', None)
    if code is None:
        return redirect('/')

    access_token_url = 'https://api.weibo.com/oauth2/access_token?client_id={0}&client_secret={1}&grant_type=authorization_code&redirect_uri=http://www.muzicm.cn/login&code={2}'.format(settings.CLIENT_ID, settings.APP_SECRET, code)
    ret = requests.post(access_token_url)
    data = ret.text
    data_dict = json.loads(data)
    token = data_dict['access_token']
    uid = data_dict['uid']

    request.session['token'] = token
    request.session['uid'] = uid
    request.session['login'] = True

    # 获取用户信息
    user_info_url = 'https://api.weibo.com/2/users/show.json?access_token={0}&uid={1}'.format(token, uid)
    user_info = requests.get(user_info_url)

    user_info_dict = json.loads(user_info.text)
    request.session['screen_name'] = user_info_dict['screen_name']
    request.session['profile_image_url'] = user_info_dict['profile_image_url']

    return redirect(request.GET.get('next', '/'))


def logout(request):
    if request.session['login']:
        del request.session['login']
        del request.session['uid']
        del request.session['token']
        del request.session['screen_name']
        del request.session['profile_image_url']

        return redirect(request.GET.get('next', '/blog/'))
    else:
        return redirect('/blog/')


def reply(request, comment_id):
    if not request.session.get('login', None) and not request.user.is_authenticated():
        return redirect('/')
    parent_comment = get_object_or_404(Comment, id=comment_id)
    return render(request, 'blog/reply.html', locals())


def about_me(request):
    return render(request, 'blog/about_me.html')


def call_me(request):
    return render(request, 'blog/call_me.html')

blog/templates/blog/about_me.html
{% extends 'blog/base.html' %}

{% block title %}
    木子窗明|关于博主
{% endblock title %}

{% block content %}
    <div class="container text-center" style="min-height: 600px;">
        <h3>关于博主</h3>
        <h4>一个 Python 小白 + Django 小白 + 爬虫小白</h4>
        <br/>
        <h3>关于本站</h3>
        <h4>使用 Python + Django + bootstrap + MySQL + Django-comments 搭建</h4>
        <br/>
        <br/>
        <a class="btn btn-primary" href="{% url 'blog:blog_index' %}">返回首页</a>
    </div>
{% endblock content %}

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/media/muzicm_favicon.ico" type="image/x-icon">
    <title>{% block title %}基础模板{% endblock title %}</title>

    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">

    {% block css %}
    {% endblock css %}

    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#my-nav" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">木子窗明</a>
        </div>

        <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'blog:blog_index' %}"><span
                        class="glyphicon glyphicon-pencil"></span> 博客</a></li>
                <li><a href="/aboutme/"><span class="glyphicon glyphicon-user"></span> 关于博主</a></li>
                <li><a href="/callme/"><span class="glyphicon glyphicon-earphone"></span> 联系我们</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-book"></span> 小项目</a></li>
            </ul>
            <form class="navbar-form navbar-left" action="{% url 'blog:blog_search' %}" method="get">
                <div class="form-group">
                    <input type="text" name="keyword" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.login %}
                    <img src="{{ request.session.profile_image_url }}" class="img-rounded"
                         style="width: 30px; height: 30px;"/>
                    {{ request.session.screen_name }}
                    <a href="/logout/?next={{ request.path }}"><i class="glyphicon glyphicon-log-out"></i>&nbsp;&nbsp;注销</a>
                {% else %}
                    <li>
                        <a href="https://api.weibo.com/oauth2/authorize?client_id=2486056362&response_type=code&redirect_uri=http://www.muzicm.cn/login">
                            <i class="glyphicon glyphicon-log-in"></i> &nbsp;&nbsp;登录
                        </a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>


<div class="container">

    {% block content %}
    {% endblock content %}

    <script async src="//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"></script>

    <div class="container-fluid">
        <div class="col-md-12">
            <ul class="text-center list-unstyled" style="height: 50px; padding-top: 15px">
                <li><span>Copyright &copy; <a href="http://www.muzicm.cn">木子窗明</a></span> |
                    <span><a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备18044144号</a></span> |
                    <span id="busuanzi_container_site_pv">本站总访问量<span id="busuanzi_value_site_pv"></span>次</span>
                </li>
            </ul>
        </div>
    </div>

</div>


<button class="gototop isvisible" style="display: inline-block;"><span>返回顶部</span></button>


<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.gototop.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $(".gototop").gototop({
            position: 50,
            duration: 1250,
            visibleAt: 300,
            classname: "isvisible"
        });
    });
</script>


{% block script %}
{% endblock script %}

</body>
</html>

blog/templates/blog/call_me.html
{% extends 'blog/base.html' %}

{% block title %}
    木子窗明|联系我们
{% endblock title %}

{% block content %}
    <div class="container text-center" style="min-height: 600px;">
        <h3>联系我们</h3>
        <h4>邮箱：1269619593@qq.com</h4>
        <h4>GitHub：<a href="https://github.com/zzz12696" target="_blank">https://github.com/zzz12696</a></h4>
        <br/>
        <h4>友情链接</h4>
        <p><a href="http://www.liujiangblog.com/" target="_blank">刘江的博客及教程</a></p>
        <br/>
        <br/>
        <a class="btn btn-primary" href="{% url 'blog:blog_index' %}">返回首页</a>
    </div>
{% endblock content %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load comments %}

{% block title %}
    木子窗明|{{ entry.title }}
{% endblock title %}

{% block css %}
    <link href="{% static 'css/github.css' %}" rel="stylesheet"/>

    <style type="text/css">
    .blog-article img {
        width: auto;
        height: auto;
        max-width: 100%;
        max-height: 100%;
    }
    </style>

    <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

    <link href="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/atelier-dune.dark.css' %}" rel="stylesheet">
    <script src="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>

{% endblock css %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="panel panel-default blog-article">
                    <div class="panel-heading">
                        <h3>{{ entry.title }}</h3>
                        <p>
                            发布时间：
                            {{ entry.created_time|date:'Y年m月d日' }}
                            &nbsp;分类：
                            {% for category in entry.category.all %}
                                <a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                            {% endfor %}
                            &nbsp;标签：
                            {% for tag in entry.tags.all %}
                                <a href="{% url 'blog:blog_tag' tag.id %}">{{ tag.name }}</a>&nbsp;&nbsp;
                            {% endfor %}
                            &nbsp;浏览量：{{ entry.visiting }}
                        </p>
                    </div>

                    <div class="panel-body">

                        {% if entry.img %}
                            <img src="{{ entry.img.url }}" class="img-rounded"
                                 style=""/>
                        {% else %}
                        {% endif %}
                        <p>
                            {{ entry.body|safe }}
                        </p>

                    </div>

                </div>


                <div class="row">
                    {% get_comment_form for entry as form %}
                    {% get_comment_count for entry as comment_count %}
                    <h3>评论总数：{{ comment_count }}</h3>
                    <hr/>
                </div>

                {#                评论框#}
                {% if request.session.login or request.user.is_authenticated %}
                    <div class="row">
                        <form class="form-horizontal" action="{% comment_form_target %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="input_title" class="pull-left control-label">评论标题：</label>
                                <div class="col-md-6">
                                    <input class="form-control" name="comment_title" id="input_title"
                                           placeholder="请输入标题"
                                           required type="text">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="input_comment" class="pull-left control-label">评论内容：</label>
                                <div class="col-md-6">
                                <textarea style="resize: none;" class="form-control" rows="6" name="comment"
                                          id="input_comment" placeholder="请输入评论内容" required></textarea>
                                </div>
                            </div>

                            <span style="display: none;">{{ form.honeypot }}</span>
                            {{ form.content_type }}
                            {{ form.object_pk }}
                            {{ form.timestamp }}
                            {{ form.security_hash }}
                            <input type="hidden" name="next" value="{% url 'blog:blog_detail' entry.id %}"/>
                            <input name="parent_id" type="hidden" value="-1"/>
                            <input name="level" type="hidden" value="0"/>


                            <div class="form-group col-md-7">
                                <div class="pull-left" style="margin-left: 68px;">
                                    <button type="reset" class="btn btn-default"><span
                                            class="glyphicon glyphicon-repeat"></span>&nbsp;&nbsp;重置
                                    </button>
                                </div>

                                <div class="pull-right" style="margin-right: 12px;">
                                    <button type="submit" class="btn btn-success"><span
                                            class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;提交
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                {% else %}
                    <h4>登陆后才可以评论</h4>
                {% endif %}
                <hr/>

                {#                评论显示区#}
                <div class="row">
                    {% for comment in comment_list %}
                        <div class="single_comment" style="margin-left: {{ comment.level }}em; margin-bottom: 20px;">
                            <div>
                                {% if comment.user_img %}
                                    <img src="{{ comment.user_img }}" alt="user_image"
                                         style="width: 50px; height: 50px; border-radius: 50%; overflow: hidden; float: left; margin-left: 10px; margin-top: 5px;">
                                {% else %}
                                    <img src="/media/blog_images/default_user_image.jpg"
                                         style="width: 50px; height: 50px; border-radius: 50%; overflow: hidden; float: left; margin-left: 10px; margin-top: 5px;">
                                {% endif %}
                            </div>

                            <div class="col-md-11 comment-content"
                                 style="margin-bottom: 10px; border-bottom: 1px dashed lightgray; border-left: 1px dashed #2d7da4; padding-bottom: 5px;">
                                <strong>{{ comment.comment_title }}</strong>
                                <div>
                                    {% if comment.parent_comment %}
                                        {% if comment.user_name %}
                                            {{ comment.user_name }}
                                        {% else %}
                                            {{ request.user }}
                                        {% endif %}
                                        <i class="glyphicon glyphicon-share-alt"></i>
                                        {{ comment.parent_comment.user_name }}
                                    {% else %}
                                        By&nbsp;
                                        {% if comment.user_name %}
                                            {{ comment.user_name }}
                                        {% else %}
                                            {{ request.user }}
                                        {% endif %}
                                        &nbsp;On&nbsp;
                                    {% endif %}
                                    <em>{{ comment.submit_date }}</em>
                                    &nbsp;&nbsp;&nbsp;
                                    {% if request.session.login or request.user.is_authenticated %}
                                        <a href="{% url 'blog:comment_reply' comment.id %}">回复</a>
                                    {% endif %}
                                </div>
                                <br/>
                                <p style="margin-bottom: 0px;">{{ comment.comment }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>

            <div class="col-md-3 ">

{#                {% block toc %}#}
{##}
{#                    <div class="row">#}
{#                        <div class="widget hidden-xs hidden-sm">#}
{#                            <h3>博客目录</h3>#}
{#                            {{ entry.toc|safe }}#}
{#                        </div>#}
{#                    </div>#}
{#                {% endblock toc %}#}

                {% include 'blog/right_side_bar.html' %}

            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}
    木子窗明|博客
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">

                {% if entries %}
                    <div class="blog-item" style="border: 1px solid #eee; padding: 5px; border-radius: 10px;">
                        {% for entry in entries %}
                            <h4><a href="{{ entry.get_absolute_url }}"
                                   style="text-decoration: none; font-size: 115%; font-weight: bold;">{{ entry.title }}</a>
                            </h4>

                            {% if entry.abstract %}
                                <p style="color: #777; font-size: small;">{{ entry.abstract }}</p>
                            {% else %}
                                <p style="color: #777; font-size: small;">{{ entry.body|truncatechars:128 }}</p>
                            {% endif %}

                            <div class="blog-tags"
                                 style="font-size: 70%; color: #75878a; margin-top: 0.5em; display: inline-block; border-top: 1px #ddd solid;">
                                <ul style="list-style-type: none; padding: 0px">
                                    <li style="float: left; margin-right: 1em;">
                                        <span class="glyphicon glyphicon-time"></span>
                                        <span>{{ entry.created_time }}</span>
                                    </li>
                                    <li style="float: left; margin-right: 1em;">
                                        阅读：{{ entry.visiting }}
                                    </li>
                                    <li style="float: left; margin-right: 1em;">
                                        <span class="glyphicon glyphicon-tag"></span>
                                        {% for category in entry.category.all %}
                                            <a href="{% url 'blog:blog_category' category.id %}"
                                               style="text-decoration: none">{{ category.name }}</a>
                                        {% endfor %}
                                    </li>
                                </ul>
                            </div>
                            <hr style="margin: 15px -5px; border: 1px solid #eee;"/>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="alert alert-info" role="alert">{{ error_msg }}</div>
                {% endif %}

                <nav aria-label="Page navigation" class="text-center">
                    <ul class="pagination">
                        {{ page_html|safe }}
                    </ul>
                </nav>

            </div>
            <div class="col-md-3">
                {% include 'blog/right_side_bar.html' %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/right_side_bar.html
{% load blog_tags %}

<div class="row sidebar-container">
    <div class="widget isvisible">
        <p class="text-center">精选32首云村音乐，双击歌曲即可播放</p>
        <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=225
                src="//music.163.com/outchain/player?type=0&id=2300490929&auto=1&height=205"></iframe>
    </div>

    {% block toc %}
    {% endblock toc %}

    <div class="widget">
        <h4 class="text-center">最新文章</h4>
        {% get_recent_entries as recent_entry_list %}
        {% for entry in recent_entry_list %}
            {% if forloop.first %}
                <div class="alert alert-success" role="alert">
                    <a href="{{ entry.get_absolute_url }}" style="text-decoration: none;">{{ entry.title }}</a>
                    <br/>
                    发表于：{{ entry.created_time|date:"Y年m月d日 H:i" }}
                </div>
            {% else %}
                <div class="alert alert-success" role="alert" style="margin-top: -18px">
                    <a href="{{ entry.get_absolute_url }}" style="text-decoration: none;">{{ entry.title }}</a>
                    <br/>
                    发表于：{{ entry.created_time|date:"Y年m月d日 H:i" }}
                </div>
            {% endif %}
        {% endfor %}


    </div>

    <div class="widget">
        <h4 class="text-center">最热文章</h4>
        {% get_popular_entries as popular_entry_list %}
        {% for entry in popular_entry_list %}
            {% if forloop.first %}
                <div class="alert alert-success" role="alert">
                    <a href="{{ entry.get_absolute_url }}"
                       style="text-decoration: none;">{{ entry.title }}</a>&nbsp;<span class="badge"
                                                                                       style="background-color: salmon">{{ entry.visiting }}</span>
                    <br/>
                    发表于：{{ entry.created_time|date:"Y年m月d日 H:i" }}
                </div>
            {% else %}
                <div class="alert alert-success" role="alert" style="margin-top: -18px">
                    <a href="{{ entry.get_absolute_url }}"
                       style="text-decoration: none;">{{ entry.title }}</a>&nbsp;<span class="badge"
                                                                                       style="background-color: salmon">{{ entry.visiting }}</span>
                    <br/>
                    发表于：{{ entry.created_time|date:"Y年m月d日 H:i" }}
                </div>
            {% endif %}
        {% endfor %}


    </div>

    <div class="widget">
        <h4 class="text-center">分类</h4>
        {% get_category as category_list %}
        <ul class="list-group">
            {% for category in category_list %}
                <li class="list-group-item">
                    <a href="{% url 'blog:blog_category' category.id %}"
                       style="text-decoration: none;">{{ category.name }}</a>
                    <span class="badge">{% get_entry_count_of_category category.id %}</span>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="widget">
        <h4 class="text-center">归档</h4>
        {% archives as date_list %}
        <ul class="list-group">
            {% for date in date_list %}
                <li class="list-group-item">
                    <a href="{% url 'blog:blog_archives' date.year date.month %}" style="text-decoration: none;">
                        <i class="glyphicon glyphicon-chevron-right"></i>
                        {{ date.year }}年{{ date.month }}月
                        <span class="badge">{% get_entry_count_of_date date.year date.month %}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="widget">
        <h4 class="text-center">标签</h4>
        {% get_tags as tag_list %}
        {% for tag in tag_list %}
            <a href="{% url 'blog:blog_tag' tag.id %}"
               class="btn {% cycle 'label-default' 'label-primary' 'label-success' 'label-info' 'label-warning' 'label-danger' %}"
               style="margin: 4px; color: white">
                {{ tag.name }}
            </a>
        {% endfor %}

    </div>

    <div class="widget">
        <h4 class="text-center">RSS</h4>
        <a href="/latest/feed/" style="text-decoration: none;">
            <i class="glyphicon glyphicon-globe"></i>
            RSS订阅
        </a>

    </div>

</div>

blog/templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/test/" method="get">
    <input type="text" name="1"/>
    <input type="text" name="2"/>
    <input type="submit"/>
</form>
</body>
</html>